server {
    listen 80;
    server_name resume-tracker-demo.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name resume-tracker-demo.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/resume-tracker-demo.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/resume-tracker-demo.duckdns.org/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://backend:8000;
    }
}